/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interno.Alumnno1;
import Interno.Extras1;
import Interno.ManipulaBD;
import cjb.ci.CtrlInterfaz;
import java.io.IOException;
import java.net.URISyntaxException;
import cjb.ci.Validaciones;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DanielaGF
 */
public class RegistrarAlumnos extends javax.swing.JFrame
{

    String sex; //Para guardar el sexo
    ArrayList<Alumnno1> tmp;
    int total;

    /**
     * Creates new form Registrarse
     */
    public RegistrarAlumnos()
    {
        initComponents();

        ImageIcon icono = new ImageIcon("C:/Users/HP/Desktop/ProyectoIHC/IHC/src/Imagenes/regresa (1).png");//Aqui va la ruta de la imagen ojo tengan cuidado con esto y al final antes de hacer el jar cambiamos la ruta
        btnRegresar.setIcon(icono);

        ImageIcon icono1 = new ImageIcon("C:/Users/HP/Desktop/ProyectoIHC/IHC/src/Imagenes/salida (8).png");
        btnSalir.setIcon(icono1);

        tmp = ManipulaBD.ConsultasAlumnos("id!=", "0");
        try
        {
            System.out.println(tmp.isEmpty());
            if (!tmp.isEmpty())
            {
                total = tmp.get(tmp.size() - 1).getId() + 1;
                System.out.println(total);
            } else
            {
                total = 0;
            }
        } catch (java.lang.NullPointerException e)
        {
            total = 0;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCurp = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfAPaterno = new javax.swing.JTextField();
        tfAMaterno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfEdad = new javax.swing.JTextField();
        tfCurp = new javax.swing.JTextField();
        rbMujer = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        tfGrado = new javax.swing.JTextField();
        tfGrupo = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfNombreM = new javax.swing.JTextField();
        tfNombreP = new javax.swing.JTextField();
        tfFolio = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JPasswordField();
        tfDia = new javax.swing.JTextField();
        tfMes = new javax.swing.JTextField();
        tfAño = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Registro Alumnos ");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Apellido Meterno:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de naciemiento :");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Edad:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("CURP:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Sexo:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Grado:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Grupo:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Nombre de la madre:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del Padre");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Folio de alumno:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Correo:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Contraseña:");

        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 153, 255));
        btnRegistrar.setText("Registrase");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCurp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCurp.setText("Obtener CURP");
        btnCurp.setEnabled(false);
        btnCurp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCurpActionPerformed(evt);
            }
        });

        btnRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegresarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });

        tfNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfNombreActionPerformed(evt);
            }
        });
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfNombreKeyTyped(evt);
            }
        });

        tfAPaterno.setEnabled(false);
        tfAPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfAPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfAPaternoKeyTyped(evt);
            }
        });

        tfAMaterno.setEnabled(false);
        tfAMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfAMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfAMaternoKeyTyped(evt);
            }
        });

        jLabel18.setText("Dia");

        jLabel19.setText("Mes");

        jLabel20.setText("Año");

        tfEdad.setEnabled(false);
        tfEdad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfEdadKeyTyped(evt);
            }
        });

        tfCurp.setEnabled(false);
        tfCurp.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfCurpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfCurpKeyTyped(evt);
            }
        });

        sexo.add(rbMujer);
        rbMujer.setText("Mujer");
        rbMujer.setEnabled(false);
        rbMujer.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                rbMujerStateChanged(evt);
            }
        });

        sexo.add(rbHombre);
        rbHombre.setText("Hombre");
        rbHombre.setEnabled(false);
        rbHombre.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                rbHombreStateChanged(evt);
            }
        });

        tfGrado.setEnabled(false);
        tfGrado.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfGradoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfGradoKeyTyped(evt);
            }
        });

        tfGrupo.setEnabled(false);
        tfGrupo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfGrupoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfGrupoKeyTyped(evt);
            }
        });

        tfTel.setEnabled(false);
        tfTel.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfTelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfTelKeyTyped(evt);
            }
        });

        tfNombreM.setEnabled(false);
        tfNombreM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfNombreMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfNombreMKeyTyped(evt);
            }
        });

        tfNombreP.setEnabled(false);
        tfNombreP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfNombrePKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfNombrePKeyTyped(evt);
            }
        });

        tfFolio.setEnabled(false);
        tfFolio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfFolioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfFolioKeyTyped(evt);
            }
        });

        tfCorreo.setEnabled(false);
        tfCorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfCorreoKeyTyped(evt);
            }
        });

        tfContraseña.setEnabled(false);
        tfContraseña.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfContraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfContraseñaKeyTyped(evt);
            }
        });

        tfDia.setEnabled(false);
        tfDia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfDiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfDiaKeyTyped(evt);
            }
        });

        tfMes.setEnabled(false);
        tfMes.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfMesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfMesKeyTyped(evt);
            }
        });

        tfAño.setEnabled(false);
        tfAño.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfAñoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfAñoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(66, 66, 66)
                                .addComponent(btnRegistrar)
                                .addGap(58, 58, 58)
                                .addComponent(btnSalir)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tfAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel18)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel19)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(202, 202, 202))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(9, 9, 9))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCurp))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbMujer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfGrado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbHombre)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(btnCurp)
                            .addComponent(tfCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rbMujer)
                            .addComponent(rbHombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(tfGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnRegistrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(477, 477, 477)
                        .addComponent(btnSalir)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed
        int id = total++;
        int grado = Integer.parseInt(String.valueOf(tfGrado.getText()));
        String grupo = tfGrupo.getText();
         String apellidoP = tfAPaterno.getText();
        String apellidoM = tfAMaterno.getText();
        String nombre = tfNombre.getText();
        String fechaNa = tfDia.getText() + "/" + tfMes.getText() + "/" + tfAño.getText();
        String curp = tfCurp.getText();
        if (rbHombre.isSelected())
        {
            sex = "Mujer";
        } else
        {
            if (rbHombre.isSelected())
            {
                sex = "Hombre";
            }
        }
        int tel = Integer.parseInt(String.valueOf(tfTel.getText()));
        String nomMa = tfNombreM.getText();
        String nomPa = tfNombreP.getText();
        int folio = Integer.parseInt(String.valueOf(tfFolio.getText()));
        String correo = tfCorreo.getText();
        String contra = tfContraseña.getText();

        //AQUI SE HACE LA CONEXION CON LA BASE DE DATOS 
        ManipulaBD.AltasAlumnos(id, grado, grupo, apellidoP, apellidoM, nombre, fechaNa, curp, 
                sex, tel, nomMa, nomPa, folio, correo, contra);
        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
        id++;
        CtrlInterfaz.limpia(tfNombre, tfAPaterno, tfAMaterno, tfDia, tfMes, tfAño, tfEdad, tfCurp, tfGrado, tfGrupo, tfTel, tfNombreM, tfNombreP, tfFolio, tfCorreo, tfContraseña);
        //CtrlInterfaz.habilita(false, rbHombre, rbMujer);
        rbHombre.setEnabled(false);
        rbMujer.setEnabled(false);
        CtrlInterfaz.habilita(false, tfAPaterno, tfAMaterno, tfDia, tfMes, tfAño, tfEdad, tfCurp, tfGrado, tfGrupo, tfTel, tfNombreM, tfNombreP, tfFolio, tfCorreo, tfContraseña);
        btnRegistrar.setEnabled(false);
        btnCurp.setEnabled(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        CtrlInterfaz.limpia(tfNombre, tfAPaterno, tfAMaterno, tfDia, tfMes, tfAño, tfEdad, tfCurp, tfGrado, tfGrupo, tfTel, tfNombreM, tfNombreP, tfFolio, tfCorreo, tfContraseña);
        //CtrlInterfaz.habilita(false, rbHombre, rbMujer);
        rbHombre.setEnabled(false);
        rbMujer.setEnabled(false);
        CtrlInterfaz.habilita(false, tfAPaterno, tfAMaterno, tfDia, tfMes, tfAño, tfEdad, tfCurp, tfGrado, tfGrupo, tfTel, tfNombreM, tfNombreP, tfFolio, tfCorreo, tfContraseña);
        btnRegistrar.setEnabled(false);
        btnCurp.setEnabled(false);
        //new ControlEscolar().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCurpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCurpActionPerformed
    {//GEN-HEADEREND:event_btnCurpActionPerformed
        if (java.awt.Desktop.isDesktopSupported())
        {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE))
            {
                try
                {
                    java.net.URI uri = new java.net.URI("https://www.gob.mx/curp/");
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex)
                {
                }
            }
        }
    }//GEN-LAST:event_btnCurpActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegresarActionPerformed
    {//GEN-HEADEREND:event_btnRegresarActionPerformed
        new ControlEscolar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        Cerrar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreKeyPressed
    {//GEN-HEADEREND:event_tfNombreKeyPressed
        if (tfNombre.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfAPaterno);
        }
    }//GEN-LAST:event_tfNombreKeyPressed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreKeyTyped
    {//GEN-HEADEREND:event_tfNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfAPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAPaternoKeyPressed
    {//GEN-HEADEREND:event_tfAPaternoKeyPressed
        if (tfAPaterno.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfAMaterno);
        }
    }//GEN-LAST:event_tfAPaternoKeyPressed

    private void tfAPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAPaternoKeyTyped
    {//GEN-HEADEREND:event_tfAPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfAPaternoKeyTyped

    private void tfAMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAMaternoKeyPressed
    {//GEN-HEADEREND:event_tfAMaternoKeyPressed
        if (tfAMaterno.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfDia);
        }
    }//GEN-LAST:event_tfAMaternoKeyPressed

    private void tfAMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAMaternoKeyTyped
    {//GEN-HEADEREND:event_tfAMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfAMaternoKeyTyped

    private void tfDiaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfDiaKeyPressed
    {//GEN-HEADEREND:event_tfDiaKeyPressed
        if (tfDia.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfMes);
        }
    }//GEN-LAST:event_tfDiaKeyPressed

    private void tfDiaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfDiaKeyTyped
    {//GEN-HEADEREND:event_tfDiaKeyTyped
        if (tfDia.getText().length() == 2)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfDiaKeyTyped

    private void tfMesKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfMesKeyPressed
    {//GEN-HEADEREND:event_tfMesKeyPressed
        if (tfMes.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfAño);
        }
    }//GEN-LAST:event_tfMesKeyPressed

    private void tfMesKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfMesKeyTyped
    {//GEN-HEADEREND:event_tfMesKeyTyped
        if (tfMes.getText().length() == 2)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfMesKeyTyped

    private void tfAñoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAñoKeyPressed
    {//GEN-HEADEREND:event_tfAñoKeyPressed
        if (tfAño.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfEdad);
        }
    }//GEN-LAST:event_tfAñoKeyPressed

    private void tfAñoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfAñoKeyTyped
    {//GEN-HEADEREND:event_tfAñoKeyTyped
        if (tfAño.getText().length() != 4)
        {
            Validaciones.validaEntero(evt);
        } else
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfAñoKeyTyped

    private void tfCurpKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfCurpKeyPressed
    {//GEN-HEADEREND:event_tfCurpKeyPressed
        if (tfCurp.getText().length() == 18 && (validaCURP(tfCurp.getText())))
        {
            Validaciones.enter(this, evt, rbMujer);
            Validaciones.enter(this, evt, rbHombre);

            rbHombre.setEnabled(true);
            rbMujer.setEnabled(true);
        }
    }//GEN-LAST:event_tfCurpKeyPressed

    private void tfCurpKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfCurpKeyTyped
    {//GEN-HEADEREND:event_tfCurpKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (tfCurp.getText().length() == 18)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfCurpKeyTyped

    private void rbMujerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_rbMujerStateChanged
    {//GEN-HEADEREND:event_rbMujerStateChanged
        if (rbMujer.isSelected())
        {
            sex = "Mujer";
        }
        tfGrado.setEnabled(true);
    }//GEN-LAST:event_rbMujerStateChanged

    private void rbHombreStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_rbHombreStateChanged
    {//GEN-HEADEREND:event_rbHombreStateChanged
        if (rbHombre.isSelected())
        {
            sex = "Hombre";
        }
        tfGrado.setEnabled(true);
    }//GEN-LAST:event_rbHombreStateChanged

    private void tfGradoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfGradoKeyPressed
    {//GEN-HEADEREND:event_tfGradoKeyPressed
        if (tfGrado.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfGrupo);
        }
    }//GEN-LAST:event_tfGradoKeyPressed

    private void tfGradoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfGradoKeyTyped
    {//GEN-HEADEREND:event_tfGradoKeyTyped
        if (tfGrado.getText().length() == 1)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfGradoKeyTyped

    private void tfGrupoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfGrupoKeyPressed
    {//GEN-HEADEREND:event_tfGrupoKeyPressed
        if (tfGrupo.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfTel);
        }
    }//GEN-LAST:event_tfGrupoKeyPressed

    private void tfGrupoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfGrupoKeyTyped
    {//GEN-HEADEREND:event_tfGrupoKeyTyped
        if (tfGrupo.getText().length() == 1)
        {
            evt.consume();
        } else
        {
            Validaciones.validaAlfabeticos(evt);
        }
    }//GEN-LAST:event_tfGrupoKeyTyped

    private void tfTelKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfTelKeyPressed
    {//GEN-HEADEREND:event_tfTelKeyPressed
        if (!((tfTel.getText().isEmpty()) || (!(validaNumero(tfTel.getText(), 5)))))
        {
            Validaciones.enter(this, evt, tfNombreM);
        }
    }//GEN-LAST:event_tfTelKeyPressed

    private void tfTelKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfTelKeyTyped
    {//GEN-HEADEREND:event_tfTelKeyTyped
        if (tfTel.getText().length() == 5)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfTelKeyTyped

    private void tfNombreMKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreMKeyPressed
    {//GEN-HEADEREND:event_tfNombreMKeyPressed
        if (tfNombreM.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfNombreP);
        }
    }//GEN-LAST:event_tfNombreMKeyPressed

    private void tfNombreMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreMKeyTyped
    {//GEN-HEADEREND:event_tfNombreMKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfNombreMKeyTyped

    private void tfNombrePKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombrePKeyPressed
    {//GEN-HEADEREND:event_tfNombrePKeyPressed
        if (tfNombreP.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfFolio);
        }
    }//GEN-LAST:event_tfNombrePKeyPressed

    private void tfNombrePKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombrePKeyTyped
    {//GEN-HEADEREND:event_tfNombrePKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfNombrePKeyTyped

    private void tfFolioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfFolioKeyPressed
    {//GEN-HEADEREND:event_tfFolioKeyPressed
        if (tfFolio.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, tfCorreo);
        }
    }//GEN-LAST:event_tfFolioKeyPressed

    private void tfFolioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfFolioKeyTyped
    {//GEN-HEADEREND:event_tfFolioKeyTyped
        if (tfFolio.getText().length() == 7)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfFolioKeyTyped

    private void tfCorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfCorreoKeyPressed
    {//GEN-HEADEREND:event_tfCorreoKeyPressed
        if (!((tfCorreo.getText().isEmpty()) || (!(validaEmail(tfCorreo.getText())))))
        {
            Validaciones.enter(this, evt, tfContraseña);
        }
    }//GEN-LAST:event_tfCorreoKeyPressed

    private void tfCorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfCorreoKeyTyped
    {//GEN-HEADEREND:event_tfCorreoKeyTyped
        if (tfCorreo.getText().length() == 35)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfCorreoKeyTyped

    private void tfContraseñaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfContraseñaKeyPressed
    {//GEN-HEADEREND:event_tfContraseñaKeyPressed
        if (!(tfContraseña.getText().isEmpty()))
        {
            Validaciones.enter(this, evt, btnRegistrar);
            btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_tfContraseñaKeyPressed

    private void tfContraseñaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfContraseñaKeyTyped
    {//GEN-HEADEREND:event_tfContraseñaKeyTyped
        if (tfContraseña.getText().length() == 10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfContraseñaKeyTyped

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfEdadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfEdadKeyTyped
    {//GEN-HEADEREND:event_tfEdadKeyTyped
        if (tfEdad.getText().length() == 2)
        {
            evt.consume();
        } else
        {
            Validaciones.validaEntero(evt);
        }
    }//GEN-LAST:event_tfEdadKeyTyped

    private void tfEdadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfEdadKeyPressed
    {//GEN-HEADEREND:event_tfEdadKeyPressed
        if (tfEdad.getText().isEmpty() != true)
        {
            Validaciones.enter(this, evt, btnCurp);
            Validaciones.enter(this, evt, tfCurp);
            btnCurp.setEnabled(true);
        }
    }//GEN-LAST:event_tfEdadKeyPressed

    //VALIDACION PARA QUE INSERTE UN EMAIL COREECTO CON @ Y EL .COM 
    public boolean validaEmail(String cad)
    {
        Pattern expReg = null;
        Matcher val = null;

        expReg = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        val = expReg.matcher(cad);

        if (val.find())
        {
            return true;
        } else
        {
            return false;
        }
    }

    //VALIDA QUE SEA UNA CURP REAL
    public boolean validaCURP(String cad)
    {
        Pattern expReg = null;
        Matcher val = null;

        expReg = Pattern.compile("^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$");
        val = expReg.matcher(cad);

        if (val.find())
        {
            return true;
        } else
        {
            return false;
        }
    }

    //VALIDACION PARA EL TELEFONO
    public static boolean validaNumero(String cad, int nums)
    {
        String n = String.valueOf(nums);
        Pattern expReg = null;
        Matcher val = null;

        expReg = Pattern.compile("^[\\d]{" + n + "}$");
        val = expReg.matcher(cad);

        if (val.find())
        {
            return true;
        } else
        {
            return false;
        }
    }

    //METODO PARA PREGUNTAR SI DESEA SALIR O NO
    public void Cerrar()
    {
        String botones[] =
        {
            "Salir", "Cancelar"
        };
        int eleccion = JOptionPane.showOptionDialog(null, "¿Desea Salir?", "SALIDA", 0, 0, null, botones, this);
        if (eleccion == JOptionPane.YES_OPTION)
        {
//            System.out.println("Salio del programa con exito");
//            System.exit(eleccion);
            new InicioUsuarios().setVisible(true);
            this.setVisible(false);
        } else if (eleccion == JOptionPane.NO_OPTION)
        {
            System.out.println("Se cancelo la salida");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegistrarAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCurp;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField tfAMaterno;
    private javax.swing.JTextField tfAPaterno;
    private javax.swing.JTextField tfAño;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfCurp;
    private javax.swing.JTextField tfDia;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfFolio;
    private javax.swing.JTextField tfGrado;
    private javax.swing.JTextField tfGrupo;
    private javax.swing.JTextField tfMes;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreM;
    private javax.swing.JTextField tfNombreP;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
